{
 "title": "sport-consumer-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "timeRate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "API Calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"sport-consumer\",method=~\".+\",status=~\"2.+\",uri=~\"/api/v1/sport.*\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"sport-consumer\",method=~\".+\",status!~\"2.+\",uri=~\"/api/v1/sport.*\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"sport-consumer\"} * 100",
     "legendFormat": "sport-consumer"
    }
   ]
  },
  {
   "title": "GET /api/v1/sport",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"sport-consumer\",method=\"GET\",status=\"200\",uri=\"/api/v1/sport\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"sport-consumer\",method=\"GET\",status!=\"200\",uri=\"/api/v1/sport\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "GET /api/v1/sport/{id}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"sport-consumer\",method=\"GET\",status=\"200\",uri=\"/api/v1/sport/{id}\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"sport-consumer\",method=\"GET\",status!=\"200\",uri=\"/api/v1/sport/{id}\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "POST /api/v1/sport",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"sport-consumer\",method=\"POST\",status=\"201\",uri=\"/api/v1/sport\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"sport-consumer\",method=\"POST\",status!=\"201\",uri=\"/api/v1/sport\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "DELETE /api/v1/sport/{id}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"sport-consumer\",method=\"DELETE\",status=\"200\",uri=\"/api/v1/sport/{id}\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"sport-consumer\",method=\"DELETE\",status!=\"200\",uri=\"/api/v1/sport/{id}\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  }
 ]
}